package com.mxcst.classic.entity;

import java.util.Date;
import lombok.Data;

@Data
public class Account {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.sha_pass_hash
     *
     * @mbg.generated
     */
    private String shaPassHash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.gmlevel
     *
     * @mbg.generated
     */
    private Byte gmlevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.joindate
     *
     * @mbg.generated
     */
    private Date joindate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.last_ip
     *
     * @mbg.generated
     */
    private String lastIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.failed_logins
     *
     * @mbg.generated
     */
    private Integer failedLogins;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.locked
     *
     * @mbg.generated
     */
    private Byte locked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.last_login
     *
     * @mbg.generated
     */
    private Date lastLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.active_realm_id
     *
     * @mbg.generated
     */
    private Integer activeRealmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.expansion
     *
     * @mbg.generated
     */
    private Byte expansion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.mutetime
     *
     * @mbg.generated
     */
    private Long mutetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.locale
     *
     * @mbg.generated
     */
    private Byte locale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.os
     *
     * @mbg.generated
     */
    private String os;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.playerBot
     *
     * @mbg.generated
     */
    private Boolean playerbot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.sessionkey
     *
     * @mbg.generated
     */
    private String sessionkey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.v
     *
     * @mbg.generated
     */
    private String v;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.s
     *
     * @mbg.generated
     */
    private String s;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.email
     *
     * @mbg.generated
     */
    private String email;
}