package com.mxcst.classic.entity;

import lombok.Data;

@Data
public class AccountBanned {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_banned.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_banned.bandate
     *
     * @mbg.generated
     */
    private Long bandate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_banned.unbandate
     *
     * @mbg.generated
     */
    private Long unbandate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_banned.bannedby
     *
     * @mbg.generated
     */
    private String bannedby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_banned.banreason
     *
     * @mbg.generated
     */
    private String banreason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_banned.active
     *
     * @mbg.generated
     */
    private Byte active;
}