package com.mxcst.classic.entity;

import lombok.Data;

@Data
public class Realmlist {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realmlist.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realmlist.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realmlist.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realmlist.localAddress
     *
     * @mbg.generated
     */
    private String localaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realmlist.localSubnetMask
     *
     * @mbg.generated
     */
    private String localsubnetmask;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realmlist.port
     *
     * @mbg.generated
     */
    private Integer port;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realmlist.icon
     *
     * @mbg.generated
     */
    private Byte icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realmlist.realmflags
     *
     * @mbg.generated
     */
    private Byte realmflags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realmlist.timezone
     *
     * @mbg.generated
     */
    private Byte timezone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realmlist.allowedSecurityLevel
     *
     * @mbg.generated
     */
    private Byte allowedsecuritylevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realmlist.population
     *
     * @mbg.generated
     */
    private Float population;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realmlist.realmbuilds
     *
     * @mbg.generated
     */
    private String realmbuilds;
}