package com.mxcst.classic.mapper;

import com.mxcst.classic.entity.Realmlist;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface RealmlistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realmlist
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realmlist
     *
     * @mbg.generated
     */
    int insert(Realmlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realmlist
     *
     * @mbg.generated
     */
    int insertSelective(Realmlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realmlist
     *
     * @mbg.generated
     */
    Realmlist selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realmlist
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Realmlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realmlist
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Realmlist record);
}